// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc3l-pnbOpsjj_IytEtzZAJocaV0JpJ4o',
    appId: '1:975561407029:web:07089fe09391e4486a8f7c',
    messagingSenderId: '975561407029',
    projectId: 'new-video-8e6ed',
    authDomain: 'new-video-8e6ed.firebaseapp.com',
    storageBucket: 'new-video-8e6ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBObilzEFXJAgaIwEKyYXUJhzvMSUK2HCA',
    appId: '1:975561407029:android:1ef29b90336fe2686a8f7c',
    messagingSenderId: '975561407029',
    projectId: 'new-video-8e6ed',
    storageBucket: 'new-video-8e6ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpJVV29y60tum0_2Vv8I_k7X5MoqZQhyM',
    appId: '1:975561407029:ios:f117e429c494f75f6a8f7c',
    messagingSenderId: '975561407029',
    projectId: 'new-video-8e6ed',
    storageBucket: 'new-video-8e6ed.firebasestorage.app',
    iosBundleId: 'com.example.uusiVideo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpJVV29y60tum0_2Vv8I_k7X5MoqZQhyM',
    appId: '1:975561407029:ios:f117e429c494f75f6a8f7c',
    messagingSenderId: '975561407029',
    projectId: 'new-video-8e6ed',
    storageBucket: 'new-video-8e6ed.firebasestorage.app',
    iosBundleId: 'com.example.uusiVideo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc3l-pnbOpsjj_IytEtzZAJocaV0JpJ4o',
    appId: '1:975561407029:web:a09f32e22d3a98526a8f7c',
    messagingSenderId: '975561407029',
    projectId: 'new-video-8e6ed',
    authDomain: 'new-video-8e6ed.firebaseapp.com',
    storageBucket: 'new-video-8e6ed.firebasestorage.app',
  );
}
